baseurl = "http://mhartington.io/"
languageCode = "en-us"
title = "Mike Hartington's blog"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
disqusShortname = "mhartington"
theme = "hugo-minimalist-theme"

[params]
    site_author = "Mike Hartington"
    site_description = "The ramblings of a New Englander"
    location = "USA"
    # All paths are relative to the baseurl. Put your files
    # somewhere in the static folder.
    avatar = "http://www.gravatar.com/avatar/be834f0968111acbbc6f3bf67041c8d5?s=128"
    header_background = "img/desk.jpg"
    header_title = "Mike's Blog"
    copyright = "Powered by [Hugo](http://gohugo.io)."

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "mhartington"
    github    = "mhartington"

