baseurl = "https://mhartington.io/"
languageCode = "en-us"
title = "Mike Hartington"
# Define how many pages appear per site
# Enable comments powered by Disqus by entering your disqus shortname
theme = 'pickles'
[params]
  bio = "Developer, Advocate, Teacher"
  subtitle = "Learning everyday"

  disqus = "mhartington"
  paginate = 10

  author = "mhartington"
  authorwebsite = "https://mhartington.io" # site_author = "Mike Hartington"

  avatar = "https://www.gravatar.com/avatar/be834f0968111acbbc6f3bf67041c8d5?s=128"

  customCSS = [ "css/highlight.css", "css/override.css", "css/syntax.css"]
  customJS = ["js/highlight.js"]


  #
  google_analytics = ""
  # [author.social]
  twitter   = "mhartington"
  github    = "mhartington"


[markup]
  [markup.highlight]
    pygmentsUseClasses=false
    noClasses = false
