language: node_js

node_js:
  - "6"

sudo: false

cache:
  directories:
    - node_modules

branches:
  only:
    - master

before_script: bash ./bin/build.sh

script:
    - ls -al static/css/style.css

after_success: bash ./bin/deploy.sh

env:
  global:
  - GH_REF: github.com/mismith0227/hugo_theme_pickles.git
  - secure: "3+eJcE7w2FHiUCywL8jmk4c8M55crxZ8UYZ8sU/HQ+Q07usF/2loFCTv1kmZOs6/sYMIIdbs4E6W402eDkjL++VdQ8JWvs3b5ZHvZPlsw22gJzmoutRAhY+7zKUiAl8NyFcH5X+Co/hJL3OU747tI8pcgpY4cP4kfRetxtwP22n5ozdc5103BajgKjAQbmDDcOxjX2P/lc6Qghxwxtt6hmnT8wjwBPd3kyu9bz59bYPynlf+Igju+R+zHXKwbClNs3wcdTHXxtPl1EuOEYiMWcwGJUCwkLz7g2wVTIGkl9vbTGQqlxkobvOVdrPLoVyUlFLdQrB8t06MCUawan9K+gn0RUlo35tNGUeuuJGN8aaAgWJ2L0/QkW64qzHysHg/MfQ3KWkzUDhuVjoG/ZAW1k2pY6cBrvULPbQNC+pICbkYjHHqSUwjRp6xU7ZuLgEsDPN04lI/UGhfbVKfnpqujl4sDkTHugnwffUj76BaFT+H/g6S50v2HI9PHi6FDFRncTkR9LLpLYxdVTkr5A83m/7QOto+ZcZKKzoJeVxHZXRem2NvR090yg31bgzQv3oMopGSUOmzmbX27OwzV78XyTTYdGKcVRzZBo+oELY/tHL3UhDIyTWmdFt+FHQqHzz/rFZO3xaU/Pl5IC1YXB92pIQ9OPTqV6IaYEiwiqJuum0="
